// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"database/sql"
)

type Client struct {
	ID             int32          `json:"id"`
	PassportNumber string         `json:"passport_number"`
	FullName       string         `json:"full_name"`
	PhoneNumber    sql.NullString `json:"phone_number"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type Currency struct {
	ID               int32        `json:"id"`
	Code             string       `json:"code"`
	Name             string       `json:"name"`
	BuyRate          string       `json:"buy_rate"`
	SellRate         string       `json:"sell_rate"`
	LastRateUpdateAt sql.NullTime `json:"last_rate_update_at"`
	CreatedAt        sql.NullTime `json:"created_at"`
	UpdatedAt        sql.NullTime `json:"updated_at"`
}

type Operation struct {
	ID                 int64        `json:"id"`
	ClientID           int32        `json:"client_id"`
	OperationType      string       `json:"operation_type"`
	CurrencyID         int32        `json:"currency_id"`
	AmountCurrency     string       `json:"amount_currency"`
	AmountRub          string       `json:"amount_rub"`
	EffectiveRate      string       `json:"effective_rate"`
	OperationTimestamp sql.NullTime `json:"operation_timestamp"`
	ReceiptReference   string       `json:"receipt_reference"`
	CreatedAt          sql.NullTime `json:"created_at"`
}
