// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error)
	CreateOperation(ctx context.Context, arg CreateOperationParams) (Operation, error)
	GetClientByID(ctx context.Context, id int32) (Client, error)
	GetClientByPassport(ctx context.Context, passportNumber string) (Client, error)
	GetCurrency(ctx context.Context, id int32) (Currency, error)
	GetCurrencyByCode(ctx context.Context, code string) (Currency, error)
	GetDailyClientForeignCurrencyVolume(ctx context.Context, arg GetDailyClientForeignCurrencyVolumeParams) (string, error)
	ListClients(ctx context.Context) ([]Client, error)
	ListCurrencies(ctx context.Context) ([]Currency, error)
	ListOperations(ctx context.Context, arg ListOperationsParams) ([]ListOperationsRow, error)
	ListOperationsByClientAndDateRange(ctx context.Context, arg ListOperationsByClientAndDateRangeParams) ([]Operation, error)
	UpdateCurrency(ctx context.Context, arg UpdateCurrencyParams) (Currency, error)
}

var _ Querier = (*Queries)(nil)
